import '../models/vendor.dart';

final List<Vendor> mockVendors = [
  Vendor(
    id: 'v1',
    shopName: 'FreshMart Supermarket',
    ownerName: 'Rajesh Kumar',
    email: 'rajesh@freshmart.com',
    phone: '+91 98765 43210',
    address: '123 MG Road, Sector 15',
    city: 'Mumbai',
    gstNumber: '27AABCT1332L1ZT',
    plan: 'Premium',
    isActive: true,
    joinedDate: DateTime(2024, 1, 15),
    staffCount: 12,
    totalRevenue: 2450000,
  ),
  Vendor(
    id: 'v2',
    shopName: 'GreenBasket Groceries',
    ownerName: 'Priya Sharma',
    email: 'priya@greenbasket.com',
    phone: '+91 87654 32109',
    address: '45 Station Road',
    city: 'Delhi',
    gstNumber: '07AABCT2234M2ZS',
    plan: 'Standard',
    isActive: true,
    joinedDate: DateTime(2024, 3, 20),
    staffCount: 8,
    totalRevenue: 1820000,
  ),
  Vendor(
    id: 'v3',
    shopName: 'MegaMall Retail',
    ownerName: 'Amit Patel',
    email: 'amit@megamall.com',
    phone: '+91 76543 21098',
    address: '789 Ring Road, Phase 2',
    city: 'Ahmedabad',
    gstNumber: '24AABCT3345N3ZR',
    plan: 'Premium',
    isActive: true,
    joinedDate: DateTime(2024, 2, 10),
    staffCount: 15,
    totalRevenue: 3100000,
  ),
  Vendor(
    id: 'v4',
    shopName: 'QuickStop Convenience',
    ownerName: 'Sunita Reddy',
    email: 'sunita@quickstop.com',
    phone: '+91 65432 10987',
    address: '22 Lake View Road',
    city: 'Bangalore',
    gstNumber: '29AABCT4456O4ZQ',
    plan: 'Basic',
    isActive: false,
    joinedDate: DateTime(2024, 5, 5),
    staffCount: 4,
    totalRevenue: 650000,
  ),
  Vendor(
    id: 'v5',
    shopName: 'DailyNeeds Mart',
    ownerName: 'Vikram Singh',
    email: 'vikram@dailyneeds.com',
    phone: '+91 54321 09876',
    address: '67 Civil Lines',
    city: 'Pune',
    gstNumber: '27AABCT5567P5ZP',
    plan: 'Standard',
    isActive: true,
    joinedDate: DateTime(2024, 4, 1),
    staffCount: 6,
    totalRevenue: 1250000,
  ),
];
